### ISSUE TITLE
module 'ukbb_paths' has no attribute 'FAM_FILE_PATH'

### ISSUE THREAD

**Issue by alina-CSI** [nadavbra/ukbb_parser#1]
Dear developers of nadavbra/ukbb_parser,

after following through the installation and configuration as described on the Code page, and trying out the parser via Python, I get the error message: module 'ukbb_paths' has no attribute 'FAM_FILE_PATH' .
There is a defined FAM_FILE_PATH in my .ukbb_paths.py file but I was not able to download the .fam file as I don't have the authorization to work on genetic data of the UKB. However, the genetic data is not interesting for my project I would just like to create a table with certain ICD diagnoses. 
And this is my question: Is the .fam file really necessary to use the parser?

Kind regards and thanks in advance
Alina

**Comment by nadavbra** [comment]
Hi @alina-CSI ,

ukbb_parser was designed to facilitate genotype-phenotype experiments (such as genetic association studies, polygenic risk scores and heritability estimates). In its current form, it does require FAM file (even if you only intend to use phenotypic data), but it should be pretty easy to fix the code and decouple this dependency. Unfortunately, I don't really have the time right now to do these code changes.

If you want to use ukbb_parser, your options would be:
1) Obtain the FAM file from the UKB (I think there's a good chance they would let you have it if you ask the UKB Access Team).
2) Fabricate a FAM file. Keep in mind that ukbb_parser only needs the genetic sex and batches in this file. You can just use the same sex as in the primary CSV file for the genetic sex, and in the batch effect just put random values (because you won't need them anyway).
3) Fix the ukbb_parser code. Like I said, if you have some experience with Python and Pandas, it shouldn't be difficult. You would just need to override the function get_sample_genotyping_metadata.

I hope this helps.

**Comment by nadavbra** [comment]
Actually, looking at the code again, I think I may have already implemented that in the past.
Try to include the argument `parse_dataset_covariates_kwargs = dict(use_genotyping_metadata = False)`.

**Comment by alina-CSI** [comment]
Thank you @nadavbra Including the argument worked well.

**Comment by nadavbra** [comment]
Good, glad to hear it solved your problem.
